# Generated by Django 5.0.6 on 2025-05-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0027_alter_tournamentinstitution_adjudicators_allocated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentinstitution',
            name='adjudicators_requested',
            field=models.PositiveIntegerField(default=0, verbose_name='Adjudicator slots requested'),
        ),
        migrations.AlterField(
            model_name='tournamentinstitution',
            name='teams_requested',
            field=models.PositiveIntegerField(default=0, verbose_name='Team slots requested'),
        ),
    ]
